# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d5ce3c853a85d8a69bc1d8493efece57eb0c1c581e2502f9a01005399f6f6131a31ad6233d1784221da60368d819bdaf670b9bc9b35758931722155e94a4258b

test:
  secret_key_base: f0ce0c61f0af434fa219fdcc87be26d1b1e56086ba8f74a6a904608cad8fd0f2084af99a8a1efeb199d9e0bb3df24ee4428c5bcafc37c074ec362a7d4b9554d4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
